/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdmin;

import model.DatabaseUtility.DB4OUtil;
import model.EcoSystem;
import model.Enterprise.Enterprise;
import model.NetworkLink.Network;
import java.awt.Color;
import java.util.Iterator;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harsh
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {
    private final EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public ManageEnterpriseJPanel(EcoSystem system) {
        initComponents();
        this.system = system;
        populateComboBox();
        populateTable();
        networkJComboBox.setEnabled(true);
        enterpriseTypeJComboBox.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jRegisterTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        networkJComboBox = new javax.swing.JComboBox();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbCollegeType = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));

        jRegisterTable.setBackground(new java.awt.Color(204, 204, 204));
        jRegisterTable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jRegisterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Default", "Network Name", "Enterprise Type", "Enterprise Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jRegisterTable.setGridColor(new java.awt.Color(56, 90, 174));
        jRegisterTable.setSelectionBackground(new java.awt.Color(240, 178, 62));
        jRegisterTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegisterTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jRegisterTable);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Adobe Devanagari", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Enterprise");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Adobe Devanagari", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Network Name :");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Adobe Devanagari", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Enterprise Type :");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Adobe Devanagari", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Enterprise Name:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        networkJComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkJComboBoxActionPerformed(evt);
            }
        });

        enterpriseTypeJComboBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        enterpriseTypeJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseTypeJComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Adobe Devanagari", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("College Type :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cmbCollegeType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbCollegeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Finance", "Agriculture" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(cmbCollegeType, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(enterpriseTypeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(networkJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCollegeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        btnDelete.setBackground(new java.awt.Color(0, 51, 102));
        btnDelete.setFont(new java.awt.Font("Adobe Devanagari", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(204, 204, 204));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/del.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 51, 102));
        btnRefresh.setFont(new java.awt.Font("Adobe Devanagari", 1, 14)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(204, 204, 204));
        btnRefresh.setText("REFRESH");
        btnRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(0, 51, 102));
        btnCreate.setFont(new java.awt.Font("Adobe Devanagari", 1, 12)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(204, 204, 204));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add1.png"))); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnModify.setBackground(new java.awt.Color(0, 51, 102));
        btnModify.setFont(new java.awt.Font("Adobe Devanagari", 1, 12)); // NOI18N
        btnModify.setForeground(new java.awt.Color(204, 204, 204));
        btnModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit1.png"))); // NOI18N
        btnModify.setText("Update");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnModify, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1034, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(490, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate, btnModify});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
    try{
        networkJComboBox.setEnabled(true);
        enterpriseTypeJComboBox.setEnabled(true);
        int index=0;
        String enterpriseType="";
        Network network1=null;
        for (Network network : system.getNetworks()) {
            if(network.getNetworkName().equals((networkJComboBox.getSelectedItem())))
            {
              network1=network;
            }
            else{
                index++;
            }
        }
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();
        if(type.getValue().equals("NGO"))
        {
            enterpriseType="NGO";
        }
        if(type.getValue().equals("Restaurant"))
        {
            enterpriseType="Restaurant";
        }
        if(type.getValue().equals("Hospital"))
        {
            enterpriseType="Hospital";
        }
        if(type.getValue().equals("College"))
        {
            enterpriseType="College";
            
        }
        if(type.getValue().equals("CollegeCounsellor"))
        {
            enterpriseType="CollegeCounsellor";
        }
        String enterpriseName=txtName.getText();
        String collegeType="";
        if(txtName.getText().trim().isEmpty()|| txtName.getText()==null){
           txtName.setBorder(BorderFactory.createLineBorder (Color.blue));
           JOptionPane.showMessageDialog(this, "Validation Failed .Please check the red box");
           return;
        }
        else{
           txtName.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        if(enterpriseType.equals("College"))
        {
            collegeType=cmbCollegeType.getSelectedItem().toString();
            network1.getEnterpriseDirectory().createEnterprise(enterpriseName, enterpriseType,collegeType);
        }
        else
        {
            network1.getEnterpriseDirectory().createEnterprise(enterpriseName, enterpriseType,"");
        }
        dB4OUtil.storeSystem(system);
        System.out.println("Enterprise added succesfully");
        JOptionPane.showMessageDialog(null, "Enterprise Added Succesfully");
        reset();
        populateTable();
        }
    } 
    catch(Exception e)
    {
        throw e;
    }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
      try{
            int rowNumber=jRegisterTable.getSelectedRow();
            if(rowNumber<0)
            {
                JOptionPane.showMessageDialog(null, "Please select a row");
                return;
            }
            String oldNetwork =(jRegisterTable.getModel().getValueAt(rowNumber, 1).toString());
            String enterpriseName=txtName.getText();
            Enterprise enterprise=(Enterprise) (jRegisterTable.getModel().getValueAt(rowNumber, 0));
            enterprise.setName(enterpriseName);
            if(txtName.getText().trim().isEmpty()|| txtName.getText()==null){
           txtName.setBorder(BorderFactory.createLineBorder (Color.BLUE));
           JOptionPane.showMessageDialog(this, "Validation Failed .Please check the blue box");
           return;
        }
        else{
           txtName.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
            if(enterpriseTypeJComboBox.getSelectedItem().equals(Enterprise.EnterpriseType.NGO))
            {
                enterprise.setEnterpriseType(Enterprise.EnterpriseType.NGO.getValue());
            }
            else if(enterpriseTypeJComboBox.getSelectedItem().equals(Enterprise.EnterpriseType.College))
            {
                 enterprise.setEnterpriseType(Enterprise.EnterpriseType.College.getValue());
            }
            else if(enterpriseTypeJComboBox.getSelectedItem().equals(Enterprise.EnterpriseType.CollegeCounsellor))
            {
                 enterprise.setEnterpriseType(Enterprise.EnterpriseType.CollegeCounsellor.getValue());
            }
            else if(enterpriseTypeJComboBox.getSelectedItem().equals(Enterprise.EnterpriseType.Restaurant))
            {
                 enterprise.setEnterpriseType(Enterprise.EnterpriseType.Restaurant.getValue());
            }
             else if(enterpriseTypeJComboBox.getSelectedItem().equals(Enterprise.EnterpriseType.Hospital))
            {
                 enterprise.setEnterpriseType(Enterprise.EnterpriseType.Hospital.getValue());
            }
            int index=0;
            for(Network network:system.getNetworks())
            {
                if(network.getNetworkName().equals(oldNetwork))
                {
                    for(Enterprise enterprise1:network.getEnterpriseDirectory().getEnterprises())
                    {
                        if(enterprise1.equals(enterprise))
                        {
                           network.getEnterpriseDirectory().getEnterprises().set(index, enterprise);
                        }
                        else{
                            index++;
                        }
                    }
                }
            }
            populateTable();
            reset();
            dB4OUtil.storeSystem(system);
            System.out.println("Enterprise updated succesfully");
            JOptionPane.showMessageDialog(null, "Enterprise Updated Succesfully");
            }
       }
      catch(Exception e)
      {
          throw  e;
      }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
try{
            networkJComboBox.setEnabled(true);
            enterpriseTypeJComboBox.setEnabled(true);
        int selectedRowIndex=jRegisterTable.getSelectedRow();
        if(selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        else{
            Enterprise enterprise=(Enterprise) jRegisterTable.getValueAt(selectedRowIndex, 0);
            String networkName=(String) jRegisterTable.getValueAt(selectedRowIndex, 1);
            for(Network network : system.getNetworks())
            {
                if(network.getNetworkName().equals(networkName))
                {
                    Iterator enterprise1= network.getEnterpriseDirectory().getEnterprises().iterator();
                    
                    while (enterprise1.hasNext()) {
                        Enterprise e= (Enterprise) enterprise1.next();
                        if(e.equals(enterprise))
                        {
                            enterprise1.remove();
                            
                        }
                    }
                }
            }
            populateTable();
            dB4OUtil.storeSystem(system);
            JOptionPane.showMessageDialog(null, "Enterprise Deleted Succesfully");
            reset();
        }
    }
    catch(Exception e)
    {
        throw e;
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jRegisterTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegisterTableMouseClicked
    try{
            networkJComboBox.setEnabled(false);
            enterpriseTypeJComboBox.setEnabled(false);
           int rowNumber=jRegisterTable.getSelectedRow();
            txtName.setText(jRegisterTable.getModel().getValueAt(rowNumber, 3).toString());
            String type=jRegisterTable.getModel().getValueAt(rowNumber, 2).toString();
            for(Network networks:system.getNetworks())
            {
                if(networks.getNetworkName().equals(jRegisterTable.getModel().getValueAt(rowNumber, 1).toString()))
                {
                    networkJComboBox.setSelectedItem(networks.getNetworkName());
                }
            }
            if(type.equals(Enterprise.EnterpriseType.NGO.getValue()))
            {
                enterpriseTypeJComboBox.setSelectedItem(Enterprise.EnterpriseType.NGO);
            }
            if(type.equals(Enterprise.EnterpriseType.Restaurant.getValue()))
            {
                enterpriseTypeJComboBox.setSelectedItem(Enterprise.EnterpriseType.Restaurant);
            }
            if(type.equals(Enterprise.EnterpriseType.College.getValue()))
            {
                enterpriseTypeJComboBox.setSelectedItem(Enterprise.EnterpriseType.College);
            }
            if(type.equals(Enterprise.EnterpriseType.CollegeCounsellor.getValue()))
            {
                enterpriseTypeJComboBox.setSelectedItem(Enterprise.EnterpriseType.CollegeCounsellor);
            }
            if(type.equals(Enterprise.EnterpriseType.Hospital.getValue()))
            {
                enterpriseTypeJComboBox.setSelectedItem(Enterprise.EnterpriseType.Hospital);
            }
       }
      catch(Exception e)
      {
          throw  e;
      }
    }//GEN-LAST:event_jRegisterTableMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        networkJComboBox.setEnabled(true);
        enterpriseTypeJComboBox.setEnabled(true);
        txtName.setText("");
        
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void enterpriseTypeJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseTypeJComboBoxActionPerformed

        if(enterpriseTypeJComboBox.getSelectedItem()!=null)
        {
            if(enterpriseTypeJComboBox.getSelectedItem().toString().equals("College"))
            {
                cmbCollegeType.setVisible(true);
                jLabel6.setVisible(true);
            }
            else{
                cmbCollegeType.setVisible(false);
                jLabel6.setVisible(false);
            }
        }
    }//GEN-LAST:event_enterpriseTypeJComboBoxActionPerformed

    private void networkJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkJComboBoxActionPerformed
    private void populateComboBox()
    {
        networkJComboBox.removeAllItems();
         enterpriseTypeJComboBox.removeAllItems();
        for(Network networks:system.getNetworks())
        {
            networkJComboBox.addItem(networks.getNetworkName());
        }
        for(Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values())
        {
            enterpriseTypeJComboBox.addItem(type);
        }
    }
     private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) jRegisterTable.getModel();
        model.setRowCount(0);
        jRegisterTable.getColumnModel().getColumn(0).setMinWidth(0);
        jRegisterTable.getColumnModel().getColumn(0).setMaxWidth(0);
        if(system.getNetworks()==null)
        {
            return;
        }
        for(Network network : system.getNetworks())
        {
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterprises())
            {
                Object[] row = new Object[5];
                    row[0]=enterprise;
                    row[1] = network.getNetworkName();
                    row[2] = enterprise.getEnterpriseType();
                    row[3] = enterprise.getName();
                    
                    model.addRow(row);
            }
        }
        
    }    

    private  void reset()
    {
        txtName.setText("");
            networkJComboBox.setSelectedIndex(0);
            enterpriseTypeJComboBox.setSelectedIndex(0);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbCollegeType;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jRegisterTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
